name: .NET Main Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, rc-** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Restore CSharp examples dependencies
      working-directory: ./Examples/CSharp
      run: dotnet restore
    - name: Build CSharp examples
      working-directory: ./Examples/CSharp
      run: dotnet build --no-restore
    - name: Restore FSharp examples dependencies
      working-directory: ./Examples/FSharp
      run: dotnet restore
    - name: Build FSharp examples
      working-directory: ./Examples/FSharp
      run: dotnet build --no-restore
    - name: Install formatter
      run: dotnet tool update --global dotnet-format
    - name: Diagnose Formatting
      run: dotnet format --check --verbosity diagnostic
    - name: Test
      run: dotnet test --no-build --verbosity normal
